# Generated by Django 4.0.5 on 2022-07-14 23:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_resume_city_alter_resume_cover_letter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=200, null=True)),
                ('qualification', models.CharField(choices=[('NQF 5 - Certificate', 'NQF 5 - Certificate'), ('NQF 5 - Higher Certificate', 'NQF 5 - Higher Certificate'), ('NQF 5 - First Diploma', 'NQF 5 - First Diploma'), ('NQF 6 - Batchelors Degree', 'NQF 6 - Batchelors Degree'), ('NQF 6 - Professional first degree postgraduate', 'NQF 6 - Professional first degree postgraduate'), ('NQF 6 - General first degree', 'NQF 6 - General first degree'), ('NQF 7 - Postgraduate Diploma', 'NQF 7 - Postgraduate Diploma'), ('NQF 7 - Honours Degree', 'NQF 7 - Honours Degree'), ('NQF 7 - Masters Degree', 'NQF 7 - Masters Degree'), ('NQF 8 - Doctors Degree', 'NQF 8 - Doctors Degree')], default='NQF 5 - Certificate', max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('graduated', models.DateField(blank=True, null=True)),
                ('major_subject', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.resume')),
            ],
        ),
    ]
