# Generated by Django 4.0.5 on 2022-07-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('NQF 5 - Certificate', 'NQF 5 - Certificate'), ('NQF 5 - Higher Certificate', 'NQF 5 - Higher Certificate'), ('NQF 5 - First Diploma', 'NQF 5 - First Diploma'), ('NQF 6 - Batchelors Degree', 'NQF 6 - Batchelors Degree'), ('NQF 6 - Professional first degree postgraduate', 'NQF 6 - Professional first degree postgraduate'), ('NQF 6 - General first degree', 'NQF 6 - General first degree'), ('NQF 7 - Postgraduate Diploma', 'NQF 7 - Postgraduate Diploma'), ('NQF 7 - Honours Degree', 'NQF 7 - Honours Degree'), ('NQF 7 - Masters Degree', 'NQF 7 - Masters Degree'), ('NQF 8 - Doctors Degree', 'NQF 8 - Doctors Degree')], default='NQF 5 - Certificate', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
