# Generated by Django 4.0.7 on 2022-09-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_jobs_closing_date_remove_jobs_enquires_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='urlLink',
            new_name='url_link',
        ),
        migrations.AddField(
            model_name='jobs',
            name='rating',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
