# Generated by Django 4.0.5 on 2022-08-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_category_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='type',
            field=models.CharField(blank=True, choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('RT', 'Remote'), ('N/A', 'N/A')], default='FT', max_length=10, null=True),
        ),
    ]
