# Generated by Django 4.0.7 on 2022-09-03 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_urllink_jobs_url_link_jobs_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='date_posted',
        ),
    ]
