# Generated by Django 4.0.7 on 2022-09-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_jobs_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='date_posted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
