# Generated by Django 4.0.7 on 2022-10-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
