# Generated by Django 4.0.7 on 2022-09-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobs_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
