# Generated by Django 4.0.7 on 2022-10-07 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_contract_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='contract_type',
        ),
    ]
