# Generated by Django 4.0.7 on 2022-09-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_rename_jobs_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
