# Generated by Django 4.0.7 on 2022-10-07 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_job_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contract_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.contract_type'),
        ),
    ]
