# Generated by Django 4.0.7 on 2022-08-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scraping_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_link', models.URLField(blank=True, null=True)),
                ('cron_job_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
