# Generated by Django 4.0.7 on 2022-08-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scraping_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Scraping_Services',
        ),
    ]
