# Generated by Django 4.0.7 on 2022-08-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_scraping_service_delete_scraping_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraping_service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
