# Generated by Django 4.0.7 on 2022-09-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_scraping_service_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('tag_description', models.CharField(blank=True, max_length=100, null=True)),
                ('tag_search_compnay', models.CharField(blank=True, max_length=100, null=True)),
                ('tag_search_category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
