# Generated by Django 4.0.7 on 2022-09-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_filter_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_tag',
            name='tag_search_category',
            field=models.CharField(blank=True, help_text='Categories to search for, separated by comma (,). Leave blank if interested in Company only.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='filter_tag',
            name='tag_search_compnay',
            field=models.CharField(blank=True, help_text='Companies name to search for, separated by comma (,). Leave blank if interested in Category only.', max_length=100, null=True),
        ),
    ]
