# Generated by Django 4.0.7 on 2022-09-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_filter_tag_tag_search_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter_tag',
            old_name='tag_search_compnay',
            new_name='tag_search_company',
        ),
        migrations.AlterField(
            model_name='filter_tag',
            name='tag_description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
