# Generated by Django 4.0.7 on 2022-09-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_rename_tag_search_compnay_filter_tag_tag_search_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_tag',
            name='tag_name',
            field=models.CharField(blank=True, help_text='Tag name to use for filtering. Must be unique.', max_length=25, null=True, unique=True),
        ),
    ]
