# Generated by Django 4.0.7 on 2022-10-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_filter_tag_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter_tag',
            name='search_url',
            field=models.URLField(blank=True, help_text='URL to search for. Leave blank. As it is auto generated.', null=True),
        ),
    ]
