# Generated by Django 4.0.7 on 2022-10-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_filter_tag_search_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter_tag',
            name='tag_search_location',
            field=models.CharField(blank=True, help_text='Locations to search for', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='filter_tag',
            name='search_url',
            field=models.URLField(blank=True, help_text="Automatically generated..Readonly Field can't be edited", null=True),
        ),
        migrations.AlterField(
            model_name='filter_tag',
            name='tag_search_company',
            field=models.CharField(blank=True, help_text='Companies name to search for', max_length=100, null=True),
        ),
    ]
