# Generated by Django 4.0.7 on 2022-11-05 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_job_full_job_qualifactions_dutes_all'),
        ('services', '0014_alter_filter_tag_tag_search_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter_tag',
            name='tag_contract_type',
            field=models.ForeignKey(blank=True, help_text='Contract type to search for', null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.contract_type'),
        ),
        migrations.AddField(
            model_name='filter_tag',
            name='tag_date_posted',
            field=models.CharField(blank=True, choices=[('Last 24 Hours', 'Last 24 Hours'), ('Last 3 Days', 'Last 3 Days'), ('Last 7 Days', 'Last 7 Days'), ('Last 14 Days', 'Last 14 Days'), ('Last 30 Days', 'Last 30 Days'), ('Last 60 Days', 'Last 60 Days'), ('Last 90 Days', 'Last 90 Days')], help_text='Date posted to search for', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='filter_tag',
            name='tag_degree',
            field=models.CharField(blank=True, choices=[('No Degree', 'No Degree'), ('High School', 'High School'), ('Associate', 'Associate'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctorate', 'Doctorate'), ('Professional', 'Professional'), ('Other', 'Other'), ('Not Specified', 'Not Specified'), ('Vocational', 'Vocational'), ('Certification', 'Certification'), ('Diploma', 'Diploma'), ('GED', 'GED')], help_text='Degree to search for', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='filter_tag',
            name='tag_experience_level',
            field=models.CharField(blank=True, choices=[('No Experience', 'No Experience'), ('1-3 Years', '1-3 Years'), ('4-5 Years', '4-5 Years'), ('6++', 'More than 6 Years')], help_text='Experience level to search for', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='filter_tag',
            name='tag_role',
            field=models.ForeignKey(blank=True, help_text='Role to search for', null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.role'),
        ),
    ]
